export const startPhrases = [
    "STARTING IN",
    "COMMENCING IN",
    "INITIATING IN",
    "COUNTDOWN FOR",
    "TAKING OFF IN",
    "EMBARKING IN",
    "COMMENCEMENT IN",
    "SWITCHING IT UP IN",
    "PREPARING TO START IN",
    "RE-ESTABLISHING 56K MODEM CONNECTION IN",
    "COME ON AND SLAM AND WELCOME TO THE JAM IN",
    "ENTERING THE RACE IN",
    "ENTERING IN",
    "MAKING SOUNDS IN",
    "HELL YES IN",
    "UNDER WAY IN",
    "SIT TIGHT FOR",
    "FAINT YELLING FOR",
    "PREPARE YOURSELVES FOR",
    "MANIFESTING IN",
    "GET READY!!! FOR",
    "PUSH PLAY IN",
    "JOINING THE RACE IN",
    "T-MINUS",
    "ENTERING THE FRAY IN",
    "PREPARE FOR LIFT-OFF IN",
    "SOMEBODY RECOMMEND ME A GOOD BOOK TO READ IN",
    "YOU HAVE",
    "HYPE INTENSIFYING FOR",
    "STAND BY FOR",
    "WASTING",
    "QUEUE FOR",
    "KICKING UP DUST IN",
    "BEGIN IN",
    "PRESS PLAY ON TAPE IN",
    "THE EXPERIENCE BEGINS IN",
    "COUNTING DOWN FOR",
    "WAITING FOR",
    "START IN",
    "ENGINES ON, YOU HAVE",
    "TAKING A QUICK BREAK FOR",
    "BEGINNING IN",
    "AUDIO START IN",
    "INCOMING IN",
    "PARTYING IN",
    "DOING THIS ONE IN",
    "HI, MY NAME IS",
    "FACESCRUNCH FOR",
    "HAVING FUN IN",
    "ANTICIPATION BUILDING FOR",
    "WE WILL START IN",
    "IT WILL BEGIN IN",
    "HOLD ON FOR",
    "THE FUN BEGINS IN",
    "STOPPING TIME FOR",
    "COMMENCING COUNTDOWN:",
    "LIFT-OFF IN",
    "ARRIVING LATE TO THE PARTY IN",
    "lower case letters for",
    "FOCUSING ENERGY FOR",
    "MEDITATING FOR",
    "ALLOW",
    "IDLE ANIMATION FOR",
    "PRETENDING TO BE A TREE FOR",
    "PAUSING FOR",
    "STARTING UP IN",
    "ACTIVATION!!! IN",
    "DISPENSING FRESH JUICE IN",
    "CHAINSAW PIT REOPENING IN",
    "ROTATING FOR",
    "RETICULATING SPLINES FOR",
    "LAUNCHING THE MISSILES IN",
    "DAYDREAMING FOR",
    "ROWING A LITTLE BOAT FOR",
    "QUARANTINING FOR",
    "EXPLAINING THE PLOT FOR",
    "UHHHHHHHHHH",
    "お前はもう死んでいる",
    "STUCK IN TIME LOOP FOR",
    "OWO             ",
    "MIKU'S GETTING PUMPED!!! ",
    "PLOTTING FOR",
    "FIXING BUGS FOR",
    "SOFT PIANO CHORDS FOR",
    "PLEASE INSERT DISK 2, YOU HAVE",
    "SYSTEM REBOOT IN",
    "HORSE NOISES HAPPENING IN",
    "BLOCKING TRAFFIC IN",
    "PRETENDING TO BE A GHOST FOR",
    "Hey, I know that today was tough. I know that you’re going through a lot lately, but you have to listen to me. You’re doing fine. You’re amazing, and you are noticed and loved. Keep it up, ok?",
    "NO FUSS FOR",
    "GIRL GAMING MOMENT IN",
    "GAMER LANGUAGE ACTIVATING IN",
]

export const emoji = [
    "1️⃣",
    "2️⃣",
    "3️⃣",
    "4️⃣",
    "5️⃣",
    "6️⃣",
    "7️⃣",
    "8️⃣",
    "9️⃣",
    "🔟",
    "🅰️",
    "🅱️",
    "🅾️",
    "🔴",
    "🟠",
    "🟡",
    "🟢",
    "🔵",
    "🟣",
    "🟤",
    "⚫",
    "⚪",
    "🔷",
    "🔶",
    "⬆️",
    "↗️",
    "➡️",
    "↘️",
    "⬇️",
    "↙️",
    "⬅️",
    "↖️",
    "♉",
    "♐",
    "♊",
    "♑",
    "♌",
    "♎",
    "♓",
    "♋",
    "♒",
    "♈",
    "♍",
    "♏",
    "⛎",
    "🐺",
    "🦊",
    "🦝",
    "🐴",
    "🦄",
    "🐍",
    "🐂",
    "🐏",
    "🦂",
    "🦀",
    "🐉",
    "🐎",
    "🏎️",
    "⚽",
    "⚾",
    "🥎",
    "🏀",
    "🏐",
    "🎹",
    "🎺",
    "🎻",
    "🎬",
    "🎮",
    "🚲",
    "🔥",
    "💧",
    "🚀",
    "🏁",
    "🌂",
    "🌐",
    "🌎",
    "☀️",
    "🌕",
    "🌘",
    "🌗",
    "🪐",
    "⭐",
    "✨",
    "🌊",
    "🌴",
    "🌳",
    "🌱",
    "🍂",
    "🍁",
    "🌸",
]
